default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: register_rails_api_development

test:
  <<: *default
  database: register_rails_api_test

production:
  <<: *default
  database: register_rails_api_production
  username: register_rails_api
  password: <%= ENV["REGISTER_RAILS_API_DATABASE_PASSWORD"] %>
